# Recording parameters
videoFolder: "./test"
camSettings: "./campy/cameras/basler/settings/acA1920-150uc_1152x1024p_100fps_trigger_RGB_p6.pfs"
frameRate: 100
recTimeInSec: 10

# Camera parameters
cameraMake: "basler"
numCams: 1
cameraNames: ['Camera1']

# Compression parameters
ffmpeg_path: [] #["/home/usr/Documents/ffmpeg/ffmpeg"]
gpus: [0]
pixelFormatInput: "rgb24" # 'bayer_bggr8' 'rgb24'
pixelFormatOutput: "rgb0"
quality: "21"

# Display parameters
chunkLengthInSec: 30
displayFrameRate: 10
displayDownsample: 2